### ISSUE TITLE
on old/slow broccoli-rollup

### ISSUE THREAD

**Issue by stefanpenner** [asakusuma/ember-rollup#12]
https://github.com/asakusuma/ember-rollup/blob/master/package.json#L25

1.2.0 dramatically improves no-change rebuilds: https://github.com/chadhietala/broccoli-rollup/pull/25

**Comment by twokul** [comment]
I think this can be closed via https://github.com/asakusuma/ember-rollup/commit/5252b92f0ca1862d20b1be7c0ee476621e591fa0

**Comment by asakusuma** [comment]
Yes,  `0.3.7` released last night

**Comment by stefanpenner** [comment]
Sweet thanks!
