### ISSUE TITLE
CI issue

### ISSUE THREAD

**Issue by xg-wang** [asakusuma/ember-rollup#34]
> error ember-cli@3.3.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*".

We should either roll back ember-cli version or update travis config and engine version requirements.

**Comment by asakusuma** [comment]
Hmmm, this appears to only be happening for your PR. I don't see the error in other PRs: https://github.com/asakusuma/ember-rollup/pull/37

**Comment by xg-wang** [comment]
Well, It's because I switched to yarn in my PR, apparently yarn has some extra check on the engine

**Comment by asakusuma** [comment]
@xg-wang ok I updated the travis config. closing.
